.\"
.\" mate-about manual page.
.\" (C) 2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH MATE-ABOUT 1 "MATE"
.SH NAME
mate-about \- Learn more about MATE
.SH SYNOPSIS
.B mate-about [\-\-mate-version]
.SH DESCRIPTION
The \fImate-about\fP program is a tool to learn more about MATE and
who creates MATE. It contains an introduction about the project, and
lists all contributors.
.PP
The list of contributors used by \fImate-about\fP is the list of
MATE Foundation members.
.SH OPTIONS
The following options are supported:
.TP
.I "--mate-version"
Output the MATE version instead of running a graphical interface.
.SH BUGS
If you find bugs in the \fImate-about\fP program, please report
these on http://bugzilla.gnome.org.
