.\"
.\" mate-color-select manual page.
.\" (C) 2015 Mike Gabriel <mike.gabriel@das-netzwerkteam.de>
.\"
.TH mate-color-select 1 "MATE"
.SH NAME
mate-color-select \- Select a color from a palette or from screen
.SH SYNOPSIS
.B mate-color-select [<gtk-options>]
.SH DESCRIPTION
The \fImate-color-select\fP program is a tool to pick a color from a
color palette or from screen. It is not meant to be used on its own, but
as a MATE Desktop helper application.
.SH OPTIONS
The \fBmate-color-select\fR tool supports all known GTK options, but has no options of its own.
.SH BUGS
If you find bugs in the \fImate-color-select\fP program, please report
these on https://github.com/mate-desktop/mate-desktop/issues.
