#!/bin/bash

# fill it
pkgname=mate-desktop
pkgver=2011.10.29
pkgrel=1
pkgdesc="Library with common API for various MATE modules"
depends=('mate-conf' 'gtk2-engines-pixbuf')
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static --disable-scrollkeeper || return 1

	make || return 1
	make DESTDIR="$pkgdir" install || return 1

	# prevent conflicts errors
	mv "${pkgdir}/usr/share/omf" "${pkgdir}/usr/share/mate-omf"
	#rm -rf ${pkgdir}/usr/share/omf
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
